export const MESSAGE_ERROR_OTP = {
  DEACTIVATED: 'deactivated',
  DEACTIVATED_CODE: 'XXX',
  INVALID_CODE_MESSAGE: 'invalid code',
  INVALID_CODE: '40102',
  COUNTDOWN_CODE: '40309',
  COUNTDOWN_ATTEMPT_CODE: '40307'
}