export const DECORATOR = {
  ROLE_AUTH_GUARD_OPTIONS: 'ROLE_AUTH_GUARD_OPTIONS',
  ACCESS_PERMISSION_AUTH_GUARD_OPTIONS: 'ACCESS_PERMISSION_AUTH_GUARD_OPTIONS',
  RESPONSE_SERIALIZER_OPTIONS: 'RESPONSE_SERIALIZER_OPTIONS',
};
