export const ORION_REPOSITORY = {
  SQL: {
    OPERATOR_AND: 'AND',
    OPERATOR_EQUAL: '=',
    OPERATOR_GREATER: '>',
    OPERATOR_GREATER_EQUAL: '>=',
    OPERATOR_IN: 'IN',
    OPERATOR_IS: 'IS',
    OPERATOR_LESS: '<',
    OPERATOR_LESS_EQUAL: '<=',
    OPERATOR_LIKE: 'LIKE',
    OPERATOR_NOT_EQUAL: '!=',
    OPERATOR_NOT_IN: 'NOT IN',
    OPERATOR_NOT_NULL: 'NOT NULL',
    OPERATOR_NULL: 'NULL',
    OPERATOR_OR: 'OR',
  },
};
