#!/bin/sh
tar czf sicepat-tms-api.tar.gz dist patches node_modules ecosystem.json package.json package-lock.json ormconfig.js ormconfig.production.js
echo "copy file to server staging Mobile API =================================="
scp sicepat-tms-api.tar.gz ubuntu@172.31.13.194:~
echo "copy file to server staging Workers API ================================="
scp sicepat-tms-api.tar.gz ubuntu@172.31.10.238:~
rm sicepat-tms-api.tar.gz

ssh ubuntu@172.31.13.194 <<'ENDSSH'
  echo "Extract File on Staging Server =================================="
  mv /home/ubuntu/sicepat-tms-api.tar.gz /home/ubuntu/sicepat-tms-api/
  cd /home/ubuntu/sicepat-tms-api/
  tar xf sicepat-tms-api.tar.gz
  rm sicepat-tms-api.tar.gz
  export NODE_ENV="production"
  pm2 startOrRestart ecosystem.json
  echo "startOrRestart server =================================="
  exit
ENDSSH

ssh ubuntu@172.31.10.238 <<'ENDSSH'
  echo "Extract File on Staging Server =================================="
  mv /home/ubuntu/sicepat-tms-api.tar.gz /home/ubuntu/sicepat-tms-api/
  cd /home/ubuntu/sicepat-tms-api/
  tar xf sicepat-tms-api.tar.gz
  rm sicepat-tms-api.tar.gz
  export NODE_ENV="production"
  pm2 startOrRestart ecosystem.json
  echo "startOrRestart server =================================="
  exit
ENDSSH
