#!/bin/sh
tar czf sicepat-tms-api.tar.gz dist patches node_modules ecosystem.json
scp sicepat-tms-api.tar.gz ubuntu@18.138.172.59:~
echo "copy file to server ======================================"
rm sicepat-tms-api.tar.gz
ssh ubuntu@18.138.172.59 <<'ENDSSH'
  mv /home/ubuntu/sicepat-tms-api.tar.gz /var/www/api-jenkins/releases/
  echo "Testing Deploy =================================="
  cd /var/www/api-jenkins/releases/
  foldername=$(date +%Y%m%d)
  mkdir -p "$foldername"
  tar xf sicepat-tms-api.tar.gz -C "$foldername"
  rm sicepat-tms-api.tar.gz
  ln -s /var/www/api-jenkins/releases/"$foldername" /var/www/api-jenkins/releases/current
  echo "link shared config ==========================="
  ln -s /var/www/api-jenkins/shared/ormconfig.js /var/www/api-jenkins/releases/"$foldername"/ormconfig.js
  mv /var/www/api-jenkins/releases/current /var/www/api-jenkins
  cd /var/www/api-jenkins/releases/"$foldername"
  pm2 startOrRestart ecosystem.json
  echo "startOrRestart server =================================="
  exit
ENDSSH