#!/bin/sh
tar czf sicepat-tms-api.tar.gz dist ormconfig.js ormconfig.production.js package.json package-lock.json yarn.lock ecosystem.json
scp sicepat-tms-api.tar.gz ubuntu@18.138.172.59:~
echo "copy file to server ======================================"
rm sicepat-tms-api.tar.gz
ssh ubuntu@18.138.172.59 <<'ENDSSH'
  mv /home/ubuntu/sicepat-tms-api.tar.gz /var/www/api-jenkins/
  echo "Testing Deploy =================================="
  cd /var/www/api-jenkins
  mkdir releases
  tar xf sicepat-tms-api.tar.gz -C releases
  rm sicepat-tms-api.tar.gz
  exit
ENDSSH