FORMAT: 1A
HOST: http://tmsapi-staging2.sicepat.com

# API Auth

# Group Auth

## Login Access [/api/auth/login]

### Login URL [POST]

+ Request Login (application/json)

    + Attributes (object)
        + clientId: `mobile`, (string, required) - Client id
        + email: `ade@sicepat.com`, (string) - User Email
        + username: `adefast`, (string) - Username User
        + password: `1234`, (string) - Password User
        + grant: `asdasgsdafwerrer345`, (string) - Refresh Token

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "userId": 11,
                "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ",
                "refreshToken": "8asfgasgwetw4tewtggg",
                "email": "ade@sicepat.com",
                "username": "adefast",
                "displayName": "Ade"
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}

## Permission Access [/api/auth/permissionAccess]
    Untuk dapetkan akses permission sebenarnya hanya butuh roleId. BranchId dikirim hanya untuk indikasi dia login sebagai cabang/gerai mana, tujuannya hanya limit akses untuk boleh buka cabang lain / tidak, selain itu untuk indicator ketika scan, bisa tau dari cabang/gerai mana

### Permission Access URL [POST]

+ Request Permission Access (application/json)

    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + clientId: `mobile`, (string, required) - Client id
        + roleId: 123, (number) - Role Id User
        + branchId: 12, (number) - Branch Id User

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "userId": 11,
                "email": "ade@sicepat.com",
                "username": "adefast",
                "displayName": "Ade",
                "branchName": "Kantor Pusat",
                "branchCode": "0010000",
                "roleName": "Sales",
                "employeeId": "1",
                "rolesAccessPermissions": [
                    "work_order_list",
                    "do_pickup_list",
                    "awb_search",
                    "awb_list",
                    "bag_list"
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Get Permission Roles [/api/auth/permissionRoles]

### Get Permission Roles URL [POST]

+ Request Get Permission Access (application/json)

    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + clientId: 'mobile', (string, required) - Client id

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "userId": 11,
                "email": "ade@sicepat.com",
                "username": "adefast",
                "displayName": "Ade",
                "roles": [
                    {
                        "roleId" : "1",
                        "branchId": "1",
                        "branchName": "Kantor Pusat",
                        "branchCode": "100000",
                        "roleName": "Sales"
                    },
                    {
                        "roleId" : "10",
                        "branchId": "2",
                        "branchName": "Pluit",
                        "branchCode": "100100",
                        "roleName": "Sigesit"
                    },
                    {
                        "roleId" : "10",
                        "branchId": "3",
                        "branchName": "Daan Mogot",
                        "branchCode": "100200",
                        "roleName": "Sigesit"
                    },
                    {
                        "roleId" : "5",
                        "branchId": "3",
                        "branchName": "Daan Mogot",
                        "branchCode": "100200",
                        "roleName": "Kepala Kurir"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Logout [/api/auth/logout]

### logout URL [POST]

+ Request Logout (application/json)

    + Header

            Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + clientId: 'mobile', (string, required) - Client id

+ Response 200 (application/json; charset=utf-8)
    + Body

            {

            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}