FORMAT: 1A
HOST: http://api.tms.sicepat.com

# API Data POD for Web & Mobile

# Group Dropdown

## Branch List [/master/branch/list]

### Branch List [POST]

+ Request Branch (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + search    : `abc` (string)
        + page      : 1, (number) - Default 1
        + limit     : 10, (number) - Default 10
        + sortBy    : branchName, (string)
        + sortDir   : asc, (string)
        + filters: (array)
            + item:
                + field   : branchCode (string)
                + operator : ilike (string) - ilike, eq, lt, gt, in, nin
                + value   : abc (string)

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 4,
                    "limit": 10
                },
                "data": [
                    {
                        "branchId": "1",
                        "branchCode": "10020010",
                        "branchName": "Pluit 2"
                    },
                    {
                        "branchId": "2",
                        "branchCode": "10020013",
                        "branchName": "Daan Mogot"
                    },
                    {
                        "branchId": "3",
                        "branchCode": "10020011",
                        "branchName": "Pluit 1"
                    },
                    {
                        "branchId": "4",
                        "branchCode": "10020012",
                        "branchName": "Pusat"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Employee List [/master/employee/list]

### Employee List [POST]

+ Request Employee (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + search    : `abc` (string)
        + page      : 1, (number) - Default 1
        + limit     : 10, (number) - Default 10
        + sortBy    : employeeName, (string)
        + sortDir   : asc, (string)
        + filters: (array)
            + item:
                + field     : employeeId (string)
                + operator  : ilike (string) - ilike, eq, lt, gt, in, nin
                + value     : `001` (string)

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 3,
                    "limit": 100
                },
                "data": [
                    {
                        "employeeId": "1",
                        "nik": "10020010",
                        "employeeName": "ABC"
                    },
                    {
                        "employeeId": "2",
                        "nik": "10020012",
                        "employeeName": "ABCD"
                    },
                    {
                        "employeeId": "3",
                        "nik": "10020013",
                        "employeeName": "ABCE"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Customer List [/master/customer/list]

### Customer List [POST]

+ Request Customer (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + search    : `abc` (string)
        + page      : 1, (number) - Default 1
        + limit     : 10, (number) - Default 10
        + sortBy    : customerName, (string)
        + sortDir   : asc, (string)
        + filters: (array)
            + item:
                + field     : customerId (string)
                + operator  : ilike (string) - ilike, eq, lt, gt, in, nin
                + value     : `001` (string)
  

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 3,
                    "limit": 100
                },
                "data": [
                    {
                        "customerId": "1",
                        "customerCode": "10020010",
                        "customerName": "ABC"
                    },
                    {
                        "customerId": "2",
                        "customerCode": "10020012",
                        "customerName": "ABCD"
                    },
                    {
                        "customerId": "3",
                        "customerCode": "10020013",
                        "customerName": "ABCE"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}

## Partner Logistic List [/master/partnerLogistic/list]

### Partner Logistic List [POST]

+ Request Partner Logistic (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + search    : `abc` (string)
        + page      : 1, (number) - Default 1
        + limit     : 10, (number) - Default 10
        + sortBy    : partnerLogisticName, (string)
        + sortDir   : asc, (string)
        + filters   : (array)
            + item:
                + field     : partnerLogisticId (string)
                + operator  : ilike (string) - ilike, eq, lt, gt, in, nin
                + value     : `001` (string)
  

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 3,
                    "limit": 100
                },
                "data": [
                    {
                        "partnerLogisticId": "1",
                        "partnerLogisticName": "ABCd",
                        "partnerLogisticEmail": "ab@gmail.com"
                    },
                    {
                        "partnerLogisticId": "2",
                        "partnerLogisticName": "ABCe",
                        "partnerLogisticEmail": "ac@gmail.com"
                    },
                    {
                        "partnerLogisticId": "3",
                        "partnerLogisticName": "ABCf",
                        "partnerLogisticEmail": "ad@gmail.com"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}

## Status Resi [/master/awbStatus/list]

### Status Resi [POST]

+ Request Status Resi (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
    

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 3,
                    "limit": 100
                },
                "data": [
                    {
                        "awbStatusId": "30000",
                        "awbStatusName": "DLV",
                        "awbStatusTitle": "DELIVERED"
                    },
                    {
                        "awbStatusId": "20000",
                        "awbStatusName": "CC",
                        "awbStatusTitle": "CRISS CROSS"
                    },
                    {
                        "awbStatusId": "14000",
                        "awbStatusName": "ANT",
                        "awbStatusTitle": "ANTAR"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}

## Reason List [/master/reason/list]

### Reason List [POST]

+ Request Reason List (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + filters   : (object)
            + apps_code    : tms (string), - hardcode `tms`
            + reason_category  : pod (string) - hardcode `pod`

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 3,
                    "limit": 100
                },
                "data": [
                    {
                        "reasonId": "1",
                        "reasonName": "NTH",
                        "reasonCode": "Not At Home"
                    },
                    {
                        "reasonId": "1",
                        "reasonName": "COPA",
                        "reasonCode": "Alamat Tutup"
                    },
                    {
                        "reasonId": "1",
                        "reasonName": "NR",
                        "reasonCode": "Barang Not Ready"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Role List [/master/role/list]

### Role List [POST]

+ Request Role List (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 0,
                    "prevPage": 0,
                    "totalPage": 1,
                    "totalData": 3,
                    "limit": 100
                },
                "data": [
                    {
                        "roleId": "1",
                        "roleName": "Superadmin"
                    },
                    {
                        "roleId": "2",
                        "roleName": "Admin"
                    },
                    {
                        "roleId": "3",
                        "roleName": "Sigesit"
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}