FORMAT: 1A
HOST: http://api.tms.sicepat.com

# API POD for Web

# Group Resi Bag

## Resi Bag [/mobile/dashboard]
    Untuk mendapatkan nomor Gabungan Paket

## resi gabungan [/web/pod/resiBag/Gab]
    Untuk Scan In Gerai dari Web POD gabungan Paket

### Scan In URL [POST]

+ Request Scan In Gabungan Paket (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + tujuan : Bandung selatan (string),
        + employeeName: Adry (string),
        + delivery_date: 2019-05-28 12:00:00,
        + description: scan gabungan paket test (string)



+ Response 200 (application/json; charset=utf-8)
    + Body
            {
                "bagNumber" : 421694,
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}