FORMAT: 1A
HOST: http://api.tms.sicepat.com

# API POD for Mobile

# Group Dashboard

## Dashboard [/mobile/dashboard]
    Untuk mendapatkan summary yang akan muncul pada Halaman Utama

### Dashboard List URL [POST]

+ Request Dashboard (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "data": [
                    "today_awb_cod"                 : 246000,
                    "today_pod_problem"             : 457,
                    "today_delivery"                : 457,
                    "today_cod_value"               : 1234567,
                    "today_cod_value_not_transfer"  : 234590,
                    "this_week_delivery"            : 246000,
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Check In [/mobile/checkIn]
    Untuk melakukan check in pada saat tiba di gerai

### Check In URL [POST]

+ Request Check In (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)

        + employeeId        : `123456`, (string, required),
        + branchId          : `000129`, (string, required),
        + dateCheckIn       : `2019-05-01 00:00:00`, (string, required),
        + longitudeCheckIn  : `106.865036` (string, required),
        + latitudeCheckIn   : `-6.175110` (string, required)

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "branchName"    : "Pluit",
                "checkInDate"   : "2019-05-01 00:00:00",
                "status"        : "ok",
                "message"       : "success"
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Check Out [/mobile/checkOut]
    Untuk melakukan check out pada saat keluar dari gerai

### Check Out URL [POST]

+ Request Check Out (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)

        + employeeId        : `123456`, (string, required),
        + branchId          : `000129`, (string, required),
        + dateCheckOut       : `2019-05-01 00:00:00`, (string, required),
        + longitudeCheckOut  : `106.865036` (string, required),
        + latitudeCheckOut   : `-6.175110` (string, required)

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "branchName"    : "Pluit",
                "checkOutDate"  : "2019-05-01 00:00:00",
                "status"        : "error",
                "message"       : "Anda belum melakukan check in gerai. Mohon untuk melakukan check in terlebih dahulu."
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)

# Group Delivery List

## Delivery List [/mobile/delivery/list]
    Untuk menampilkan Daftar Pengantaran Sigesit pada Mobile

### Delivery List URL [POST]

+ Request Delivery In List (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + filters           : (object)
            + employeeId            : `1`, (string, required)
            + startDeliveryDateTime : `2019-05-01 00:00:00`, (string, required)
            + endDeliveryDateTime   : `2019-05-01 00:00:00`, (string, required)
        + page              : 1, (number) - Default 1
        + limit             : 10, (number) - Default 10
        + sortBy            : deliveryDateTime, (string)
        + sortDir           : desc, (string)


+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 2,
                    "prevPage": 0,
                    "totalPage": 8,
                    "totalData": 798,
                    "limit": 100
                },
                "data": [
                    {
                        "awbId"                 : 1,
                        "awbNumber"             : "0001",
                        "merchant"              : "Tokopedia",
                        "consigneeName"         : "Andy Suryono",
                        "consigneeAddress"      : "Jl. Tanjung Duren",
                        "consigneeNumber"       : "+628123456789",
                        "packageType"           : "best",
                        "packageTypeName"       : "Best",
                        "productType"           : "doc",
                        "isCOD"                 : true,
                        "awbStatusId"           : 21500,
                        "awbStatusName"         : "Antar Ulang",
                        "redeliveryHistory"     : [
                            {
                                "historyDate"   : "2019-05-16",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-16 16:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                    {
                                        "historyDateTime"   : "2019-05-16 12:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                    {
                                        "historyDateTime"   : "2019-05-16 10:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                ],
                            },
                            {
                                "historyDate"   : "2019-05-15",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-15 16:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Budi",
                                    },
                                ],
                            },
                            {
                                "historyDate"   : "2019-05-14",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-14 00:00:00",
                                        "reasonDescription" : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                ]
                            }
                        ],
                        "specialInstruction"    : [
                            "Foto di Tempat",
                            "DO Balik"
                        ]
                    },
                    {
                        "awbId"                 : 1,
                        "awbNumber"             : "0002",
                        "merchant"              : "Tokopedia",
                        "consigneeName"         : "Andy Suryono",
                        "consigneeAddress"      : "Jl. Tanjung Duren",
                        "consigneeNumber"       : "+628123456789",
                        "packageType"           : "best",
                        "packageTypeName"       : "Best",
                        "productType"           : "doc",
                        "isCOD"                 : true,
                        "awbStatusId"           : 21500,
                        "awbStatusName"         : "Antar Ulang",
                        "redeliveryHistory"     : [
                            {
                                "historyDate"   : "2019-05-16",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-16 16:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                    {
                                        "historyDateTime"   : "2019-05-16 12:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                    {
                                        "historyDateTime"   : "2019-05-16 10:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                ],
                            },
                            {
                                "historyDate"   : "2019-05-15",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-15 16:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Budi",
                                    },
                                ],
                            },
                            {
                                "historyDate"   : "2019-05-14",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-14 00:00:00",
                                        "reasonDescription" : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                ]
                            }
                        ],
                        "specialInstruction"    : [
                            "Foto di Tempat",
                            "DO Balik"
                        ]
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


# Group Mobile Sync

## Sent Data [/mobile/sentData]
    Untuk mengirimkan data dari mobile ke web

### Dashboard List URL [POST]

+ Request Dashboard (application/json)
    + Header

        Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)

        + awb : (object)
            + awbId             : `1`, (string),
            + receivedDateTime  : `2019-05-01 00:00:00`, (string)
            + longitude         : `106.865036` (string),
            + latitude          : `-6.175110` (string),
            + reasonId          : 6 (number),
            + employeeId        : `12345` (string),
            + podNotes          : `abc` (string),
            + reasonNotes       : `abc` (string),
            + photoPod          : `images` (string),
            + signPod           : `images` (string)
        + dateSend : `2019-05-01 00:00:00`, (string)


+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "totalData"     : 2,
                "totalSuccess"  : 1,
                "totalError"    : 1,
                "data" : [
                    {
                        "awbNumber" : "0001",
                        "status"    : "ok",
                        "message"   : "success",
                    },
                    {
                        "awbNumber": "0002",
                        "status"    : "error",
                        "message"   : "Status sudah delivered (20-05-2019 16:00:00)",
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}

# Group History POD

## History POD List [/mobile/historyPOD]
    Untuk menampilkan daftar riwayat POD yang sudah dilakukan

### History POD List URL [POST]

+ Request History POD List (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + filters           : (object)
            + awbNumber            : `000012981212`, (string, required)
            + startPodDateTime : `2019-05-01 00:00:00`, (string, required)
            + endPodDateTime   : `2019-05-01 00:00:00`, (string, required)
        + page              : 1, (number) - Default 1
        + limit             : 10, (number) - Default 10
        + sortBy            : consigneeName, (string)
        + sortDir           : desc, (string)


+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                "paging": {
                    "currentPage": 1,
                    "nextPage": 2,
                    "prevPage": 0,
                    "totalPage": 8,
                    "totalData": 798,
                    "limit": 100
                },
                "data": [
                    {
                        "awbId"                 : 1,
                        "awbNumber"             : "0001",
                        "merchant"              : "Tokopedia",
                        "consigneeName"         : "Andy Suryono",
                        "consigneeAddress"      : "Jl. Tanjung Duren",
                        "consigneeNumber"       : "+628123456789",
                        "packageType"           : "best",
                        "packageTypeName"       : "Best",
                        "productType"           : "doc",
                        "isCOD"                 : true,
                        "awbStatusId"           : 30000,
                        "awbStatusName"         : "Delivered",
                        "photoPod"              : "https://sicepatmasterdata.s3-ap-southeast-1.amazonaws.com/attachments/pickup-images/2019/6/19/5860_photo1560948461357.jpg",
                        "signPod"              : "https://sicepatmasterdata.s3-ap-southeast-1.amazonaws.com/attachments/pickup-images/2019/6/19/5860_photo1560948461357.jpg",
                    },
                    {
                        "awbId"                 : 1,
                        "awbNumber"             : "0002",
                        "merchant"              : "Tokopedia",
                        "consigneeName"         : "Andy Suryono",
                        "consigneeAddress"      : "Jl. Tanjung Duren",
                        "consigneeNumber"       : "+628123456789",
                        "packageType"           : "best",
                        "packageTypeName"       : "Best",
                        "productType"           : "doc",
                        "isCOD"                 : true,
                        "awbStatusId"           : 22000,
                        "awbStatusName"         : "BAD ADDRESS",
                        "photoPod"              : "https://sicepatmasterdata.s3-ap-southeast-1.amazonaws.com/attachments/pickup-images/2019/6/19/5860_photo1560948461357.jpg",
                        "signPod"              : "https://sicepatmasterdata.s3-ap-southeast-1.amazonaws.com/attachments/pickup-images/2019/6/19/5860_photo1560948461357.jpg",
                        "redeliveryHistory"     : [
                            {
                                "historyDate"   : "2019-05-16",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-16 16:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                    {
                                        "historyDateTime"   : "2019-05-16 12:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                    {
                                        "historyDateTime"   : "2019-05-16 10:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                ],
                            },
                            {
                                "historyDate"   : "2019-05-15",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-15 16:00:00",
                                        "reasonCode"        : "NTH",
                                        "reasonNote"        : "Gagal DO Not At Home",
                                        "employeeName"      : "Budi",
                                    },
                                ],
                            },
                            {
                                "historyDate"   : "2019-05-14",
                                "list"          : [
                                    {
                                        "historyDateTime"   : "2019-05-14 00:00:00",
                                        "reasonDescription" : "Gagal DO Not At Home",
                                        "employeeName"      : "Anto",
                                    },
                                ]
                            }
                        ]
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}


## Update Status Redelivery [/mobile/historyPOD/updateStatus]
    Untuk melakukan update status redelivery

### Update Status Redelivery URL [POST]

+ Request Update Status Redelivery (application/json)
    + Header

        Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)

        + awbId             : `1`, (string),
        + updatedTime       : `2019-05-01 00:00:00`, (string)


+ Response 200 (application/json; charset=utf-8)
    + Body

            {
                    "awbNumber" : "0001",
                    "status"    : "ok",
                    "message"   : "success"
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {}

+ Response 401 (application/json; charset=utf-8)
    + Body

            {}
