--
-- PostgreSQL database dump
--

-- Dumped from database version 10.6
-- Dumped by pg_dump version 10.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: reason; Type: TABLE DATA; Schema: public; Owner: sicepatstaging
--

INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (1, 'tms', 'pickup', 'problem', 'NTH', 'Not At Home', NULL, 166, '2019-01-09 18:09:45', 166, '2019-01-09 18:09:45', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (2, 'tms', 'pickup', 'problem', 'NET', 'Not Enough Time', NULL, 166, '2019-01-09 18:10:42', 166, '2019-01-09 18:10:42', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (3, 'tms', 'pickup', 'problem', 'BA', 'Bad Adress', NULL, 166, '2019-01-09 18:13:18', 166, '2019-01-21 15:59:42', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (4, 'tms', 'pickup', 'problem', 'BEN', 'Bencana Alam', NULL, 166, '2019-01-09 18:14:56', 166, '2019-01-21 16:00:11', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (5, 'tms', 'pickup', 'problem', 'MSB', 'Musibah ', NULL, 166, '2019-01-21 16:01:35', 166, '2019-01-21 16:01:35', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (6, 'tms', 'pickup', 'problem', 'NR', 'Barang Not Ready', NULL, 166, '2019-01-21 16:01:58', 166, '2019-01-21 16:01:58', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (7, 'tms', 'pickup', 'problem', 'SA', 'Salah Assign', NULL, 166, '2019-01-21 16:02:07', 166, '2019-01-21 16:02:07', false, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (8, 'tms', 'pickup', 'accepted', 'DTM', 'Diterima', NULL, 166, '2019-01-21 16:02:34', 166, '2019-01-21 16:02:34', true, true, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (9, 'tms', 'pickup', 'problem', 'CP', 'Cancel PU', NULL, 166, '2019-03-15 11:34:06', 166, '2019-03-15 11:34:06', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (10, 'tms', 'pickup', 'problem', 'CBS', 'Cancel By Seller', NULL, 166, '2019-04-15 15:49:22', 166, '2019-04-15 15:49:22', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (11, 'tms', 'pickup', 'problem', 'CPU', 'Cancel PU', NULL, 4234, '2019-04-16 20:11:13', 4234, '2019-04-16 20:11:13', true, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (12, 'tms', 'pod', 'problem', 'CC', 'Criss Cross', NULL, 4234, '2019-07-04 14:00:22', 4234, '2019-07-04 14:01:06', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (15, 'tms', 'pod', 'problem', 'AU', 'Antar Ulang Besok', NULL, 4234, '1900-01-20 14:01:07', 4234, '1900-01-20 14:01:07', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (16, 'tms', 'pod', 'problem', 'BA', 'Bad Address', NULL, 4234, '1900-01-20 14:01:08', 4234, '1900-01-20 14:01:08', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (17, 'tms', 'pod', 'problem', 'MR', 'Misroute', NULL, 4234, '1900-01-20 14:01:09', 4234, '1900-01-20 14:01:09', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (19, 'tms', 'pod', 'problem', 'LOST', 'Hilang', NULL, 4234, '1900-01-20 14:01:11', 4234, '1900-01-20 14:01:11', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (20, 'tms', 'pod', 'problem', 'BROKEN', 'Rusak', NULL, 4234, '1900-01-20 14:01:12', 4234, '1900-01-20 14:01:12', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (21, 'tms', 'pod', 'problem', 'RTN', 'Retur Pusat', NULL, 4234, '1900-01-20 14:01:13', 4234, '1900-01-20 14:01:13', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (22, 'tms', 'pod', 'problem', 'RTS', 'Retur To Shipper', NULL, 4234, '1900-01-20 14:01:14', 4234, '1900-01-20 14:01:14', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (23, 'tms', 'pod', 'problem', 'HOLD', 'Hold / Pending', NULL, 4234, '1900-01-20 14:01:15', 4234, '1900-01-20 14:01:15', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (24, 'tms', 'pod', 'problem', 'RTA', 'Retur Gerai', NULL, 4234, '1900-01-20 14:01:16', 4234, '1900-01-20 14:01:16', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (25, 'tms', 'pod', 'problem', 'CODB', 'COD Bermasalah (CODB)', NULL, 4234, '1900-01-20 14:01:17', 4234, '1900-01-20 14:01:17', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (26, 'tms', 'pod', 'problem', 'OTS', 'On Transit Schedule', NULL, 4234, '1900-01-20 14:01:18', 4234, '1900-01-20 14:01:18', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (27, 'tms', 'pod', 'problem', 'OSD', 'Rescheduled Delivery', NULL, 4234, '1900-01-20 14:01:19', 4234, '1900-01-20 14:01:19', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (28, 'tms', 'pod', 'accepted', 'YBS', 'Yangn Bersangkutan', NULL, 4234, '1900-01-20 14:01:20', 4234, '1900-01-20 14:01:20', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (29, 'tms', 'pod', 'accepted', 'ART', 'Asistan Rumah Tangga', NULL, 4234, '1900-01-20 14:01:21', 4234, '1900-01-20 14:01:21', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (30, 'tms', 'pod', 'accepted', 'PK', 'Penjaga Kost', NULL, 4234, '1900-01-20 14:01:22', 4234, '1900-01-20 14:01:22', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (31, 'tms', 'pod', 'accepted', 'KRY', 'Karyawan', NULL, 4234, '1900-01-20 14:01:23', 4234, '1900-01-20 14:01:23', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (32, 'tms', 'pod', 'accepted', 'RSP', 'Resepsionis', NULL, 4234, '1900-01-20 14:01:24', 4234, '1900-01-20 14:01:24', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (33, 'tms', 'pod', 'accepted', 'SCY', 'Security', NULL, 4234, '1900-01-20 14:01:25', 4234, '1900-01-20 14:01:25', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (34, 'tms', 'pod', 'accepted', 'KEL', 'Keluarga Serumah', NULL, 4234, '1900-01-20 14:01:26', 4234, '1900-01-20 14:01:26', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (35, 'tms', 'pod', 'accepted', 'SU/IST', 'Suami/Istri', NULL, 4234, '1900-01-20 14:01:27', 4234, '1900-01-20 14:01:27', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (36, 'tms', 'pod', 'accepted', 'TTG', 'Tetangga', NULL, 4234, '1900-01-20 14:01:28', 4234, '1900-01-20 14:01:28', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (37, 'tms', 'pod', 'accepted', 'TMN', 'Teman', NULL, 4234, '1900-01-20 14:01:29', 4234, '1900-01-20 14:01:29', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (13, 'tms', 'pod', 'problem', 'CU', 'Cnee Unknown', NULL, 4234, '2019-07-04 14:00:43', 4234, '2019-07-04 14:00:43', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (14, 'tms', 'pod', 'problem', 'NTH', 'Not At Home', NULL, 4234, '1900-01-20 14:01:06', 4234, '1900-01-20 14:01:06', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (38, 'tms', 'pod_cod', 'problem', 'CODB 1', 'Tidak Merasa Pesan', NULL, 4234, '2019-07-04 14:40:58', 4234, '2019-07-04 14:40:58', false, false, true);
INSERT INTO public.reason (reason_id, apps_code, reason_category, reason_type, reason_code, reason_name, reason_description, user_id_created, created_time, user_id_updated, updated_time, is_deleted, is_reschedule_pickup, is_reschedule) VALUES (18, 'tms', 'pod', 'problem', 'CODA', 'Closed Once Delivery Attempt', NULL, 4234, '1900-01-20 14:01:10', 4234, '1900-01-20 14:01:10', false, false, true);


--
-- PostgreSQL database dump complete
--

